from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
SECRET_KEY = os.getenv("SECRET_KEY")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", 30))
REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS", 30))
RESEND_API_KEY = os.getenv("RESEND_API_KEY")


POINTS_PER_CITY_LEVEL = 12
RIDE_REWARD_MULTIPLIER = 50
MAX_RIDE_POOL_SIZE = 10
RIDE_REFRESH_INTERVAL = 180
RIDE_EXPIRATION_SECONDS = 30
FUEL_COST_MULTIPLIER = 2
